apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: inference-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: lscr.io/linuxserver/nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-full
          mountPath: /mnt/config
        - name: nginx-logs
          mountPath: /var/log/nginx
        - name: config-writable
          mountPath: /config
        - name: config-volume
          mountPath: /config.json
          subPath: config.json
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: etcnginx.conf
        env:
        - name: NGINX_AUTORELOAD
          value: "true"
      - name: nginx-monitor
        image: ghcr.io/thegreatgooo/homelabsmith-nginx-endpoint-activity-monitor:latest
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
          readOnly: true
        - name: config-volume
          mountPath: /config.json
          subPath: config.json
      volumes:
      - name: nginx-config-full
        configMap:
          name: nginx-config-map
      - name: nginx-logs
        emptyDir: {}
      - name: config-volume
        configMap:
          name: nginx-config-map
          items:
          - key: nginx.conf
            path: nginx.conf
          - key: config.json
            path: config.json
          - key: etcnginx.conf
            path: etcnginx.conf
      - name: config-writable
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: inference-manager
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer