apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
  namespace: inference-manager
data:
  etcnginx.conf: |
    include /mnt/config/nginx.conf;
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        server {
            listen 80;
            server_name localhost;
            
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
        }
    }
    daemon off;
    pid /run/nginx.pid;
  config.json: |
    [
        {
            "pattern": "/api/users",
            "endpoint": "http://localhost:8080/health"
        },
        {
            "pattern": "/api/products",
            "endpoint": "http://localhost:8080/heartbeat"
        }
    ]