apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-service-config
  namespace: inference-manager
data:
  INFERENCE_SERVICE_URL: "http://inference-service:5002"
  MODEL_MONITOR_SERVICE_URL: "http://model-monitor-service:5003"
  PROXY_HOSTNAME: "localhost"
  SERVER_NAME: "inference-service"
  WOL_SERVICE_URL: "http://wol-service:8080/wake"
  OPEN_WEBUI_URL: "http://open-webui:8080"