name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '18 16 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push each service's Docker image
      - name: Build and push inference-service
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./inference-service
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-inference-service:${{ github.sha }}
          labels: |
            org.opencontainers.image.title=inference-service
            org.opencontainers.image.version=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/TheGreatGooo/HomeLabSmith

      - name: Build and push model-monitor-service
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./model-monitor-service
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-model-monitor-service:${{ github.sha }}
          labels: |
            org.opencontainers.image.title=model-monitor-service
            org.opencontainers.image.version=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/TheGreatGooo/HomeLabSmith

      - name: Build and push nginx-endpoint-activity-monitor
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./nginx-endpoint-activity-monitor
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-nginx-endpoint-activity-monitor:${{ github.sha }}
          labels: |
            org.opencontainers.image.title=nginx-endpoint-activity-monitor
            org.opencontainers.image.version=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/TheGreatGooo/HomeLabSmith

      - name: Build and push shutdown-service
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./shutdown-service
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-shutdown-service:${{ github.sha }}
          labels: |
            org.opencontainers.image.title=shutdown-service
            org.opencontainers.image.version=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/TheGreatGooo/HomeLabSmith

      - name: Build and push wol-service
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./wol-service
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-wol-service:${{ github.sha }}
          labels: |
            org.opencontainers.image.title=wol-service
            org.opencontainers.image.version=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/TheGreatGooo/HomeLabSmith

      # Sign the resulting Docker image digests except on PRs.
      - name: Sign the published Docker images
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-inference-service:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-model-monitor-service:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-nginx-endpoint-activity-monitor:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-shutdown-service:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-wol-service:${{ github.sha }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}